apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: hello-world-app
spec:
  components:
    - name: frontend
      type: component
      image: radixdev.azurecr.io/hello-world-app:latest
      ports:
        - name: http
          port: 80
      environmentConfig:
        - environment: dev
          replicas: 1
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"